//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummoningBell
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryListing
    {
        public int Id { get; set; }
        public int Player { get; set; }
        public int ServerItem { get; set; }
        public int Price { get; set; }
        public bool HQ { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ItemByServer ItemByServer { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
