//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummoningBell
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemByServer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemByServer()
        {
            this.HistoryListings = new HashSet<HistoryListing>();
            this.MarketListings = new HashSet<MarketListing>();
        }
    
        public int ServerItemId { get; set; }
        public int ItemId { get; set; }
        public int Server { get; set; }
        public Nullable<System.DateTime> LastChecked { get; set; }
        public int Priority { get; set; }
        public int LowestPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryListing> HistoryListings { get; set; }
        public virtual Item Item { get; set; }
        public virtual Server Server1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketListing> MarketListings { get; set; }
    }
}
