//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummoningBell
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketListing
    {
        public int Id { get; set; }
        public int Retainer { get; set; }
        public int ServerItem { get; set; }
        public int Price { get; set; }
        public bool HQ { get; set; }
        public short City { get; set; }
        public string Quantity { get; set; }
        public string Materia1 { get; set; }
        public string Materia2 { get; set; }
        public string Materia3 { get; set; }
        public string Materia4 { get; set; }
        public string Materia5 { get; set; }
    
        public virtual ItemByServer ItemByServer { get; set; }
        public virtual Retainer Retainer1 { get; set; }
    }
}
