//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummoningBell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int id { get; set; }
        public int recipeId { get; set; }
        public int CraftType { get; set; }
        public int RecipeLevel { get; set; }
        public int ResultItem { get; set; }
        public int ResultAmount { get; set; }
        public int Ingredient1 { get; set; }
        public byte IngredientAmount1 { get; set; }
        public int Ingredient2 { get; set; }
        public byte IngredientAmount2 { get; set; }
        public int Ingredient3 { get; set; }
        public byte IngredientAmount3 { get; set; }
        public int Ingredient4 { get; set; }
        public byte IngredientAmount4 { get; set; }
        public int Ingredient5 { get; set; }
        public byte IngredientAmount5 { get; set; }
        public int Ingredient6 { get; set; }
        public byte IngredientAmount6 { get; set; }
        public int Ingredient7 { get; set; }
        public byte IngredientAmount7 { get; set; }
        public int CrystalType1 { get; set; }
        public byte CrystalAmount1 { get; set; }
        public int CrystalType2 { get; set; }
        public byte CrystalAmount2 { get; set; }
        public byte RecipeElement { get; set; }
        public int RecipeNotebook { get; set; }
        public bool IsSecondary { get; set; }
        public int Difficulty { get; set; }
        public int Quality { get; set; }
        public int Durability { get; set; }
        public int RequiredCraftsmanship { get; set; }
        public int RequiredControl { get; set; }
        public int QuickSynthCraftsmanship { get; set; }
        public int QuickSynthControl { get; set; }
        public bool CanQuickSynth { get; set; }
        public bool CanHq { get; set; }
        public int RequiredItem { get; set; }
        public bool IsSpecializationRequired { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
        public virtual Item Item3 { get; set; }
        public virtual Item Item4 { get; set; }
        public virtual Item Item5 { get; set; }
        public virtual Item Item6 { get; set; }
        public virtual Item Item7 { get; set; }
        public virtual Item Item8 { get; set; }
        public virtual Item Item9 { get; set; }
        public virtual Item Item10 { get; set; }
        public virtual RecipeLevel RecipeLevel1 { get; set; }
    }
}
