//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummoningBell
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopItemMap
    {
        public long id { get; set; }
        public int Shop { get; set; }
        public int ShopItem { get; set; }
    
        public virtual Shop Shop1 { get; set; }
        public virtual ShopItem ShopItem1 { get; set; }
    }
}
